name: Prettify on Merge

on:
  pull_request_target:
    types:
      - closed

jobs:
  prettier:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Ensure the branch being merged is checked out
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write ./packages/core/**/* ./packages/cli/**/*
