name: Prettier Check on Merge

on:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # Specify which files or directories to format
          prettier_options: --write ./packages/core/**/* ./packages/cli/**/*

          # Optionally set the working directory if needed
          # working_directory: ./ # Uncomment and adjust if your setup requires a specific directory
